HomeWork25.05/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HomeWork25._05.DB;
using HomeWork25._05.DB.Repositories;
using HomeWork25._05.Models;
using Microsoft.AspNetCore.Mvc;

namespace HomeWork25._05.Controllers
{
    public class CategoryController : Controller
    {
        CategiryRepos categories { get; }
        DataContext context {get;}
        public CategoryController(DataContext _context)
        {
            context = _context;
            categories = new CategiryRepos(_context);
        }
        public IActionResult Index()
        {
            ViewBag.Customer = context.Customers.Where(p=>p.RoleId == 1).FirstOrDefault();
            ViewBag.Categories = categories.ReadCategories();
            return View();
        }
        [HttpGet]
        public IActionResult AddCategory()
        {
            ViewBag.Customer = context.Customers.Where(p=>p.RoleId == 1).FirstOrDefault();
            return View();
        }
        [HttpPost]
        public IActionResult AddCategory(string CategoryName)
        {
            ViewBag.Customer = context.Customers.Where(p=>p.RoleId == 1).FirstOrDefault();
            if (string.IsNullOrEmpty(CategoryName))
                return BadRequest();
            categories.AddCategory(new Category() { CategoryName = CategoryName});
            return RedirectToAction("Index");
        }
    }
}

HomeWork25.05/Controllers/VkhodController.cs
using System.Linq;
using HomeWork25._05.Controllers;
using HomeWork25._05.DB;
using Microsoft.AspNetCore.Mvc;

namespace HomeWork25._05
{
    public class VkhodController : Controller
    {
        DataContext context {get;}
        public VkhodController(DataContext _context)
        {
            context = _context;
        } 
        [HttpGet]
        public IActionResult Vkhod()
        {
            ViewBag.Roles = context.Roles.ToList();
            return View();
        }
        public IActionResult Vkhod(string Role, string Login, string Password)
        {
            if(string.IsNullOrEmpty(Login) && string.IsNullOrEmpty(Password))
                return BadRequest(ModelState);
            var cust = context.Customers.Where(p=> p.RoleId == int.Parse(Role) && p.Login == Login && p.Password == Password).Select(p=>p).FirstOrDefault();
            if(cust != null && Role == "1")
                return RedirectToAction("Index","Product",new {Id = cust.Id});
            if(cust != null && Role == "2")
                return RedirectToAction($"Index","Customer",new {Id = cust.Id});
            return BadRequest();
        }
    }
}

HomeWork25.05/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HomeWork25._05</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HomeWork25._05</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vkhod" asp-action="Vkhod">Home</a>
                        </li>
                        @if(ViewBag.Customer != null && ViewBag.Customer.RoleId == 1)
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="AddProduct">AddProduct</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="ProductChange">EditProduct</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="ProductDelete">DeleteProduct</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="AddCategory">AddCategory</a>
                            </li>
                        }
                        else if (ViewBag.Customer != null && ViewBag.Customer.RoleId == 2){
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Products</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="PokupkiOkno">Pokupki</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - HomeWork25._05 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

HomeWork25.05/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HomeWork25._05</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HomeWork25._05</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - HomeWork25._05 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>